"""
Final assembly script.
Takes all the independent mart_unified_chunk_*.parquet files generated by 
the MapReduce distributed processing and merges them into a single, 
final mart_unified_final.parquet ready for DataLens.
"""

import duckdb
from pathlib import Path
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

PROJECT_DIR = Path(__file__).resolve().parents[1]
MARTS_DIR = PROJECT_DIR / "data" / "marts"
INPUT_GLOB = MARTS_DIR / "mart_unified_chunk_*.parquet"
FINAL_MART = MARTS_DIR / "mart_unified_final.parquet"

def main():
    if FINAL_MART.exists():
        FINAL_MART.unlink()
        
    logging.info(f"Assembling final mart from {INPUT_GLOB}")
    
    con = duckdb.connect(database=':memory:')
    
    query = f"""
    COPY (
        SELECT * 
        FROM read_parquet('{INPUT_GLOB.as_posix()}')
        ORDER BY time_period, segment, content_tier
    ) TO '{FINAL_MART.as_posix()}' (FORMAT PARQUET, COMPRESSION 'ZSTD');
    """
    
    con.execute(query)
    logging.info(f"Success! Final mart saved to: {FINAL_MART}")
    
    # Check size and rows
    res = con.execute(f"SELECT COUNT(*), sum(slice_users_count) FROM read_parquet('{FINAL_MART.as_posix()}')").fetchone()
    logging.info(f"Final Mart Rows: {res[0]}")
    logging.info(f"Total user-item interactions captured: {res[1]:,.0f}")

if __name__ == '__main__':
    main()
